// SPDX-FileCopyrightText: Copyright (c) 2026 owu <wqh@live.com>
// SPDX-License-Identifier: GPL-3.0-only

export global AppConstants {
    // --- URLs ---
    out property <string> project_repository: "https://github.com/voorz/wsl-dashboard";
    out property <string> project_website: "https://www.wslui.com";
    out property <string> license_url: "/blob/main/LICENSE";
    out property <string> usbipd_releases: "https://github.com/dorssel/usbipd-win/releases";
    out property <string> proxy_test_default: "https://www.google.com";
    out property <string> ubuntu_wsl_images: "https://cdimages.ubuntu.com/ubuntu-wsl/";
}
