// SPDX-FileCopyrightText: Copyright (c) 2026 owu <wqh@live.com>
// SPDX-License-Identifier: GPL-3.0-only

import { ConfirmationDialog } from "dialogs/confirmation_dialog.slint";
import { ExportDialog } from "dialogs/export_dialog.slint";
import { CloneDialog } from "dialogs/clone_dialog.slint";
import { MessageDialog } from "dialogs/message_dialog.slint";
import { CheckUpdateDialog } from "dialogs/check_update_dialog.slint";
import { CheckExpiredDialog } from "dialogs/check_expired_dialog.slint";
import {
    StoreInstallWarnDialog,
} from "dialogs/store_install_warn_dialog.slint";
import { InformationDialog } from "dialogs/information_dialog.slint";
import { SettingsDialog } from "dialogs/settings_dialog.slint";
import { OperationOverlay } from "dialogs/operation_overlay.slint";
import { RootFSHelpDialog } from "dialogs/rootfs_help_dialog.slint";
import { VSCodeStartupDialog } from "dialogs/vscode_startup_dialog.slint";
import { MoveDialog } from "dialogs/move_dialog.slint";
import { WslConfigDialog } from "dialogs/wsl_config_dialog.slint";
import { NetworkAddRuleDialog } from "dialogs/network_add_rule_dialog.slint";
import { CompressDialog } from "dialogs/compress_dialog.slint";
import { WslCompatDialog } from "dialogs/wsl_compat_dialog.slint";
import { LanguageSelectDialog } from "dialogs/language_select_dialog.slint";
import { PopupNoticeDialog } from "dialogs/popup_notice.slint";
import { PopupImageDialog } from "dialogs/popup_image.slint";
import { UsbDeviceInfoDialog } from "dialogs/usb_device_info_dialog.slint";

export {
    ConfirmationDialog,
    ExportDialog,
    CloneDialog,
    MoveDialog,
    MessageDialog,
    CheckUpdateDialog,
    CheckExpiredDialog,
    StoreInstallWarnDialog,
    InformationDialog,
    SettingsDialog,
    OperationOverlay,
    RootFSHelpDialog,
    VSCodeStartupDialog,
    WslConfigDialog,
    NetworkAddRuleDialog,
    CompressDialog,
    WslCompatDialog,
    LanguageSelectDialog,
    PopupNoticeDialog,
    PopupImageDialog,
    UsbDeviceInfoDialog,
}
