// SPDX-FileCopyrightText: Copyright (c) 2026 owu <wqh@live.com>
// SPDX-License-Identifier: GPL-3.0-only

import {
    Theme,
    AppInfo,
    AppI18n,
    AboutStrings,
    LayoutConstants,
} from "../theme.slint";
import { CustomScrollbar } from "../components/scrollbar.slint";
import { ThemedIcon } from "../components/common.slint";

export component AboutView inherits VerticalLayout {
    in property <AboutStrings> strings;
    in property <image> group_pic;
    in property <bool> group_pic_ready: false;
    in-out property <bool> show_group_popup: false;
    padding-top: 0px;
    padding-bottom: 8px;
    callback open_url(string);
    callback check_update_clicked();
    callback group_clicked();
    callback close_group_popup();

    vertical-stretch: 1;

    Rectangle {
        vertical-stretch: 1;
        clip: true;

        flick := Flickable {
            viewport-height: cards_container.preferred-height;
            width: parent.width;
            height: 100%;

            cards_container := VerticalLayout {
                width: flick.width;
                spacing: 12px;
                padding-left: AppI18n.is-rtl ? 10px : 0px;
                padding-right: AppI18n.is-rtl ? 0px : 10px;

                card_top := Rectangle {
                    background: Theme.dark_mode ? Theme.card_bg : Theme.card_bg_muted;
                    border-radius: 8px;
                    border-width: 0px;
                    VerticalLayout {
                        spacing: 14px;
                        padding-left: AppI18n.is-rtl ? 24px : 12px;
                        padding-right: AppI18n.is-rtl ? 12px : 24px;
                        padding-top: 8px;
                        padding-bottom: 6px;

                        Text {
                            text: root.strings.title;
                            font-size: 14px * LayoutConstants.font-scale;
                            font-family: Theme.default_font;
                            font-weight: 500;
                            color: Theme.text_primary;
                            horizontal-alignment: AppI18n.is-rtl ? right : left;
                        }

                        Text {
                            text: root.strings.description;
                            font-size: 14px * LayoutConstants.font-scale;
                            font-family: Theme.default_font;
                            color: Theme.text_secondary;
                            wrap: word-wrap;
                            min-height: max(30px, self.preferred-height);
                            horizontal-alignment: AppI18n.is-rtl ? right : left;
                        }
                    }
                }

                card_mid := Rectangle {
                    background: Theme.dark_mode ? Theme.card_bg : Theme.card_bg_muted;
                    border-radius: 8px;
                    border-width: 0px;
                    VerticalLayout {
                        spacing: 18px;
                        padding-left: AppI18n.is-rtl ? 24px : 12px;
                        padding-right: AppI18n.is-rtl ? 12px : 24px;
                        padding-top: 8px;
                        padding-bottom: 6px;

                        HorizontalLayout {
                            spacing: 12px;
                            if (!AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{e8f3}";
                                    icon_type: "pink";
                                    font-size: 15px;
                                }
                            }
                            VerticalLayout {
                                spacing: 4px;
                                HorizontalLayout {
                                    spacing: 4px;
                                    alignment: AppI18n.is-rtl ? end : start;

                                    if (AppI18n.is-rtl): Text {
                                        text: root.strings.updates;
                                        font-size: 13px * LayoutConstants.font-scale;
                                        font-family: Theme.default_font;
                                        font-weight: 500;
                                        color: Theme.text_primary;
                                        TouchArea {
                                            mouse-cursor: pointer;
                                            clicked => {
                                                root.check_update_clicked();
                                            }
                                        }
                                    }

                                    Text {
                                        text: root.strings.version;
                                        font-size: 13px * LayoutConstants.font-scale;
                                        font-family: Theme.default_font;
                                        font-weight: 500;
                                        color: Theme.text_primary;
                                    }

                                    if (!AppI18n.is-rtl): Text {
                                        text: root.strings.updates;
                                        font-size: 13px * LayoutConstants.font-scale;
                                        font-family: Theme.default_font;
                                        font-weight: 500;
                                        color: Theme.text_primary;
                                        TouchArea {
                                            mouse-cursor: pointer;
                                            clicked => {
                                                root.check_update_clicked();
                                            }
                                        }
                                    }
                                }

                                HorizontalLayout {
                                    spacing: 4px;
                                    alignment: AppI18n.is-rtl ? end : start;

                                    if (AppI18n.is-rtl && AppInfo.checking_update): Text {
                                        text: "(" + root.strings.check_update + ")";
                                        font-size: 12px * LayoutConstants.font-scale;
                                        font-family: Theme.default_font;
                                        color: Theme.accent;
                                    }
                                    if (AppI18n.is-rtl && !AppInfo.checking_update && AppInfo.has_update): Text {
                                        text: "(" + AppI18n.t("about.new_version", [AppInfo.latest_version, AppI18n.version]) + ")";
                                        font-size: 12px * LayoutConstants.font-scale;
                                        font-family: Theme.default_font;
                                        color: #FF4D4F;
                                        TouchArea {
                                            mouse-cursor: pointer;
                                            clicked => {
                                                root.open_url(AppInfo.update_download_url);
                                            }
                                        }
                                    }
                                    Text {
                                        text: "v" + AppInfo.version;
                                        font-size: 13px * LayoutConstants.font-scale;
                                        font-family: Theme.default_font;
                                        color: Theme.text_secondary;
                                        TouchArea {
                                            mouse-cursor: pointer;
                                            clicked => {
                                                root.check_update_clicked();
                                            }
                                        }
                                    }

                                    if (!AppI18n.is-rtl && AppInfo.checking_update): Text {
                                        text: "(" + root.strings.check_update + ")";
                                        font-size: 12px * LayoutConstants.font-scale;
                                        font-family: Theme.default_font;
                                        color: Theme.accent;
                                    }
                                    if (!AppI18n.is-rtl && !AppInfo.checking_update && AppInfo.has_update): Text {
                                        text: "(" + AppI18n.t("about.new_version", [AppInfo.latest_version, AppI18n.version]) + ")";
                                        font-size: 12px * LayoutConstants.font-scale;
                                        font-family: Theme.default_font;
                                        color: #FF4D4F;
                                        TouchArea {
                                            mouse-cursor: pointer;
                                            clicked => {
                                                root.open_url(AppInfo.update_download_url);
                                            }
                                        }
                                    }
                                }
                            }

                            if (AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{e8f3}";
                                    icon_type: "pink";
                                    font-size: 15px;
                                }
                            }
                        }

                        // Project website
                        HorizontalLayout {
                            spacing: 12px;
                            if (!AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{e80f}";
                                    icon_type: "success";
                                    font-size: 15px;
                                }
                            }
                            HorizontalLayout {
                                spacing: 4px;
                                alignment: AppI18n.is-rtl ? end : start;
                                Text {
                                    text: root.strings.website + ":";
                                    font-size: 13px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    font-weight: 500;
                                    color: Theme.text_primary;
                                }

                                Text {
                                    text: AppInfo.project_website;
                                    font-size: 13px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    color: Theme.accent;
                                    TouchArea {
                                        mouse-cursor: pointer;
                                        clicked => {
                                            root.open_url(AppInfo.project_website);
                                        }
                                    }
                                }
                            }

                            if (AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{e80f}";
                                    icon_type: "success";
                                    font-size: 15px;
                                }
                            }
                        }

                        // Project repository
                        HorizontalLayout {
                            spacing: 12px;
                            if (!AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{e943}";
                                    icon_type: "navigation";
                                    font-size: 15px;
                                }
                            }
                            HorizontalLayout {
                                spacing: 4px;
                                alignment: AppI18n.is-rtl ? end : start;
                                Text {
                                    text: root.strings.repository + ":";
                                    font-size: 13px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    font-weight: 500;
                                    color: Theme.text_primary;
                                }

                                Text {
                                    text: AppInfo.project_repository;
                                    font-size: 13px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    color: Theme.accent;
                                    TouchArea {
                                        mouse-cursor: pointer;
                                        clicked => {
                                            root.open_url(AppInfo.project_repository);
                                        }
                                    }
                                }
                            }

                            if (AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{e943}";
                                    icon_type: "navigation";
                                    font-size: 15px;
                                }
                            }
                        }

                        Rectangle {
                            height: 1px;
                            background: Theme.border_color;
                        }

                        
                        // Issues
                        HorizontalLayout {
                            alignment: AppI18n.is-rtl ? end : start;
                            spacing: 12px;
                            if (!AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{ebe8}";
                                    icon_type: "danger";
                                    font-size: 15px;
                                }
                            }
                            VerticalLayout {
                                alignment: center;
                                Text {
                                    text: root.strings.issues;
                                    font-size: 13px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    color: Theme.text_primary;
                                    horizontal-alignment: AppI18n.is-rtl ? right : left;
                                    TouchArea {
                                        mouse-cursor: pointer;
                                        clicked => {
                                            root.open_url(AppInfo.issues_url);
                                        }
                                    }
                                }
                            }

                            if (AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{ebe8}";
                                    icon_type: "danger";
                                    font-size: 15px;
                                }
                            }
                        }

                        // Project Links Grid
                        GridLayout {
                            spacing-vertical: 12px;
                            spacing-horizontal: 24px;
                            
                            // Row 1
                            Row {
                                // Left Column: Documents
                                Rectangle {
                                    horizontal-stretch: 1;
                                    HorizontalLayout {
                                        alignment: AppI18n.is-rtl ? end : start;
                                        spacing: 12px;
                                        if (!AppI18n.is-rtl): Rectangle {
                                            width: 20px;
                                            ThemedIcon {
                                                y: 1px;
                                                icon_code: "\u{e8a5}";
                                                icon_type: "indigo";
                                                font-size: 15px;
                                            }
                                        }
                                        VerticalLayout {
                                            alignment: center;
                                            Text {
                                                text: root.strings.documents;
                                                font-size: 13px * LayoutConstants.font-scale;
                                                font-family: Theme.default_font;
                                                color: Theme.text_primary;
                                                horizontal-alignment: AppI18n.is-rtl ? right : left;
                                                TouchArea {
                                                    mouse-cursor: AppInfo.documents_url != "" ? pointer : default;
                                                    clicked => {
                                                        if (AppInfo.documents_url != "") {
                                                            root.open_url(AppInfo.documents_url);
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        if (AppI18n.is-rtl): Rectangle {
                                            width: 20px;
                                            ThemedIcon {
                                                y: 1px;
                                                icon_code: "\u{e8a5}";
                                                icon_type: "indigo";
                                                font-size: 15px;
                                            }
                                        }
                                    }
                                }

                                // Right Column: Announcements
                                Rectangle {
                                    horizontal-stretch: 1;
                                    HorizontalLayout {
                                        alignment: AppI18n.is-rtl ? end : start;
                                        spacing: 12px;
                                        if (!AppI18n.is-rtl): Rectangle {
                                            width: 20px;
                                            ThemedIcon {
                                                y: 1px;
                                                icon_code: "\u{e95a}";
                                                icon_type: "purple";
                                                font-size: 15px;
                                            }
                                        }
                                        VerticalLayout {
                                            alignment: center;
                                            Text {
                                                text: root.strings.announcements;
                                                font-size: 13px * LayoutConstants.font-scale;
                                                font-family: Theme.default_font;
                                                color: Theme.text_primary;
                                                horizontal-alignment: AppI18n.is-rtl ? right : left;
                                                TouchArea {
                                                    mouse-cursor: pointer;
                                                    clicked => {
                                                        root.open_url(AppInfo.announcements_url);
                                                    }
                                                }
                                            }
                                        }
                                        if (AppI18n.is-rtl): Rectangle {
                                            width: 20px;
                                            ThemedIcon {
                                                y: 1px;
                                                icon_code: "\u{e95a}";
                                                icon_type: "purple";
                                                font-size: 15px;
                                            }
                                        }
                                    }
                                }
                            }

                            // Row 2
                            Row {
                                // Left Column: Discussions (Talk)
                                Rectangle {
                                    horizontal-stretch: 1;
                                    HorizontalLayout {
                                        alignment: AppI18n.is-rtl ? end : start;
                                        spacing: 12px;
                                        if (!AppI18n.is-rtl): Rectangle {
                                            width: 20px;
                                            ThemedIcon {
                                                y: 1px;
                                                icon_code: "\u{e77b}";
                                                icon_type: "teal";
                                                font-size: 15px;
                                            }
                                        }
                                        VerticalLayout {
                                            alignment: center;
                                            Text {
                                                text: root.strings.talk;
                                                font-size: 13px * LayoutConstants.font-scale;
                                                font-family: Theme.default_font;
                                                color: Theme.text_primary;
                                                horizontal-alignment: AppI18n.is-rtl ? right : left;
                                                TouchArea {
                                                    mouse-cursor: AppInfo.talk_url != "" ? pointer : default;
                                                    clicked => {
                                                        if (AppInfo.talk_url != "") {
                                                            root.open_url(AppInfo.talk_url);
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        if (AppI18n.is-rtl): Rectangle {
                                            width: 20px;
                                            ThemedIcon {
                                                y: 1px;
                                                icon_code: "\u{e77b}";
                                                icon_type: "teal";
                                                font-size: 15px;
                                            }
                                        }
                                    }
                                }

                                // Right Column: Group
                                Rectangle {
                                    horizontal-stretch: 1;
                                    HorizontalLayout {
                                        alignment: AppI18n.is-rtl ? end : start;
                                        spacing: 12px;
                                        if (!AppI18n.is-rtl): Rectangle {
                                            width: 20px;
                                            ThemedIcon {
                                                y: 1px;
                                                icon_code: "\u{e8f2}";
                                                icon_type: "info";
                                                font-size: 15px;
                                            }
                                        }
                                        VerticalLayout {
                                            alignment: center;
                                            Text {
                                                text: root.strings.group;
                                                font-size: 13px * LayoutConstants.font-scale;
                                                font-family: Theme.default_font;
                                                color: Theme.text_primary;
                                                horizontal-alignment: AppI18n.is-rtl ? right : left;
                                                TouchArea {
                                                    mouse-cursor: pointer;
                                                    clicked => {
                                                        root.group_clicked();
                                                    }
                                                }
                                            }
                                        }
                                        if (AppI18n.is-rtl): Rectangle {
                                            width: 20px;
                                            ThemedIcon {
                                                y: 1px;
                                                icon_code: "\u{e8f2}";
                                                icon_type: "info";
                                                font-size: 15px;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                card_bottom := Rectangle {
                    background: Theme.dark_mode ? Theme.card_bg : Theme.card_bg_muted;
                    border-radius: 8px;
                    border-width: 0px;
                    VerticalLayout {
                        spacing: 12px;
                        padding-left: AppI18n.is-rtl ? 24px : 12px;
                        padding-right: AppI18n.is-rtl ? 12px : 24px;
                        padding-top: 8px;
                        padding-bottom: 6px;

                        // Labor of love
                        HorizontalLayout {
                            spacing: 12px;
                            if (!AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{e735}";
                                    icon_type: "gold";
                                    font-size: 15px * LayoutConstants.font-scale;
                                }
                            }
                            VerticalLayout {
                                spacing: 4px;

                                Text {
                                    text: root.strings.love;
                                    font-size: 14px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    font-weight: 500;
                                    color: Theme.text_primary;
                                    horizontal-alignment: AppI18n.is-rtl ? right : left;
                                }

                                Text {
                                    text: root.strings.star;
                                    font-size: 13px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    color: Theme.text_secondary;
                                    wrap: word-wrap;
                                    horizontal-alignment: AppI18n.is-rtl ? right : left;
                                }
                            }

                            if (AppI18n.is-rtl): Rectangle {
                                width: 20px;
                                ThemedIcon {
                                    y: 1px;
                                    icon_code: "\u{e735}";
                                    icon_type: "gold";
                                    font-size: 15px * LayoutConstants.font-scale;
                                }
                            }
                        }

                        // Copyright & License
                        Rectangle {
                            height: 1px;
                            background: Theme.border_color;
                        }

                        VerticalLayout {
                            spacing: 4px;
                            padding-top: 0px;
                            padding-bottom: 2px;

                            Text {
                                text: root.strings.copyright;
                                font-size: 12px * LayoutConstants.font-scale;
                                font-family: Theme.default_font;
                                color: Theme.text_secondary;
                                wrap: word-wrap;
                                horizontal-alignment: center;
                                vertical-alignment: center;
                            }

                            HorizontalLayout {
                                alignment: center;
                                spacing: 4px;

                                Text {
                                    y: -1.5px;
                                    text: "\u{e8a1}";
                                    font-size: 12px;
                                    font-family: Theme.icon_font;
                                    color: Theme.icon_color_slate;
                                    vertical-alignment: center;
                                }

                                Text {
                                    text: root.strings.license;
                                    font-size: 12px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    color: Theme.accent;
                                    vertical-alignment: center;
                                    TouchArea {
                                        mouse-cursor: pointer;
                                        clicked => {
                                            root.open_url(AppInfo.license_url);
                                        }
                                    }
                                }

                                Text {
                                    text: "|";
                                    font-size: 12px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    color: Theme.text_secondary;
                                    vertical-alignment: center;
                                }

                                Text {
                                    text: root.strings.privacy_policy;
                                    font-size: 12px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    color: Theme.accent;
                                    vertical-alignment: center;
                                    TouchArea {
                                        mouse-cursor: pointer;
                                        clicked => {
                                            root.open_url(AppInfo.project_website + "/privacy/");
                                        }
                                    }
                                }

                                Text {
                                    text: "|";
                                    font-size: 12px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    color: Theme.text_secondary;
                                    vertical-alignment: center;
                                }

                                Text {
                                    text: root.strings.terms_of_service;
                                    font-size: 12px * LayoutConstants.font-scale;
                                    font-family: Theme.default_font;
                                    color: Theme.accent;
                                    vertical-alignment: center;
                                    TouchArea {
                                        mouse-cursor: pointer;
                                        clicked => {
                                            root.open_url(AppInfo.project_website + "/terms/");
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        CustomScrollbar {
            opacity: (flick.viewport-height > flick.height) ? 1 : 0;
            visible: flick.viewport-height > flick.height;
            x: AppI18n.is-rtl ? 2px : parent.width - 8px;
            y: 0;
            width: 8px;
            height: 100%;
            maximum: flick.viewport-height - flick.height;
            page_size: flick.height;
            value: -flick.viewport-y;
            scroll_to(v) => {
                flick.viewport-y = -v;
            }
        }
    }
}
