// SPDX-FileCopyrightText: Copyright (c) 2026 owu <wqh@live.com>
// SPDX-License-Identifier: GPL-3.0-only

// Parse USB VID (u16) from a hardware ID list.
// Hardware IDs look like: "USB\VID_046D&PID_C52B&REV_1200", "USB\VID_046D&PID_C52B", etc.
pub fn parse_vid_from_hardware_ids(hardware_ids: &[String]) -> Option<u16> {
    for id in hardware_ids {
        let upper = id.to_uppercase();
        if let Some(pos) = upper.find("VID_") {
            let hex_str = &upper[pos + 4..];
            let hex4: String = hex_str.chars().take(4).collect();
            if hex4.len() == 4 {
                if let Ok(vid) = u16::from_str_radix(&hex4, 16) {
                    return Some(vid);
                }
            }
        }
    }
    None
}

// Look up USB vendor name by VID.
// Returns None if the VID is not in the built-in table.
pub fn lookup_vendor(vid: u16) -> Option<&'static str> {
    match vid {
        0x0079 => Some("DragonRise Inc."),
        0x03EB => Some("Atmel Corp."),
        0x03F0 => Some("HP Inc."),
        0x03F9 => Some("KeyTronic Corp."),
        0x0402 => Some("ALi Corp."),
        0x0403 => Some("Future Technology Devices International Ltd."),
        0x0409 => Some("NEC Corp."),
        0x040D => Some("VIA Technologies, Inc."),
        0x041E => Some("Creative Technology Ltd."),
        0x0424 => Some("Microchip Technology Inc. (SMSC)"),
        0x0430 => Some("Sun Microsystems, Inc."),
        0x0451 => Some("Texas Instruments Inc."),
        0x0457 => Some("Silicon Integrated Systems Corp."),
        0x0458 => Some("KYE Systems Corp."),
        0x045E => Some("Microsoft Corp."),
        0x0461 => Some("Primax Electronics, Ltd."),
        0x0462 => Some("Micro-Star International Co., Ltd."),
        0x046A => Some("Cherry GmbH"),
        0x046D => Some("Logitech, Inc."),
        0x046E => Some("Behavior Technology Computer Corp."),
        0x047D => Some("Kensington"),
        0x047F => Some("Plantronics, Inc."),
        0x0480 => Some("Toshiba America Inc."),
        0x0482 => Some("Kyocera Corp."),
        0x0483 => Some("STMicroelectronics"),
        0x0489 => Some("Foxconn / Hon Hai"),
        0x04A9 => Some("Canon, Inc."),
        0x04B4 => Some("Cypress Semiconductor Corp."),
        0x04BB => Some("I/O Data Device, Inc."),
        0x04C5 => Some("Fujitsu, Ltd."),
        0x04CA => Some("Lite-On Technology Corp."),
        0x04D9 => Some("Holtek Semiconductor, Inc."),
        0x04E8 => Some("Samsung Electronics Co., Ltd."),
        0x04E6 => Some("SCM Microsystems, Inc."),
        0x04F2 => Some("Chicony Electronics Co., Ltd."),
        0x04F3 => Some("Elan Microelectronics Corp."),
        0x04F9 => Some("Brother Industries, Ltd."),
        0x04FC => Some("Sunplus Technology Co., Ltd."),
        0x0502 => Some("Acer, Inc."),
        0x0547 => Some("Anchor Chips, Inc."),
        0x054C => Some("Sony Corp."),
        0x0557 => Some("ATEN International Co., Ltd."),
        0x0572 => Some("Conexant Systems (Rockwell), Inc."),
        0x057E => Some("Nintendo Co., Ltd."),
        0x0582 => Some("Roland Corp."),
        0x058F => Some("Alcor Micro Corp."),
        0x059F => Some("LaCie, Ltd."),
        0x05AC => Some("Apple, Inc."),
        0x05C6 => Some("Qualcomm, Inc."),
        0x05C8 => Some("Cheng Uei Precision Industry Co., Ltd."),
        0x05E3 => Some("Genesys Logic, Inc."),
        0x0609 => Some("SMK Manufacturing Inc."),
        0x0627 => Some("Adomax Technology Co., Ltd."),
        0x062A => Some("MosArt Semiconductor Corp."),
        0x0644 => Some("TEAC Corp."),
        0x0665 => Some("Cypress Semiconductor"),
        0x067B => Some("Prolific Technology, Inc."),
        0x0684 => Some("Actions Microelectronics Co."),
        0x06A3 => Some("Saitek PLC"),
        0x06CB => Some("Synaptics, Inc."),
        0x071D => Some("Arris Interactive L.L.C."),
        0x0781 => Some("SanDisk Corp."),
        0x07B4 => Some("Olympus Optical Co., Ltd."),
        0x07C0 => Some("Code Mercenaries Hard- und Software GmbH"),
        0x0835 => Some("Action Star Enterprise Co., Ltd."),
        0x0846 => Some("NetGear, Inc."),
        0x0853 => Some("Topre Corporation"),
        0x085C => Some("ColorVision, Inc."),
        0x0862 => Some("Logitech, Inc."),
        0x08E4 => Some("Pioneer Corp."),
        0x08EC => Some("M-Systems Flash Disk Pioneers, Ltd."),
        0x0930 => Some("Toshiba Corp."),
        0x0951 => Some("Kingston Technology"),
        0x0955 => Some("NVIDIA Corp."),
        0x09DA => Some("A4Tech Co., Ltd."),
        0x09FB => Some("Altera Corp."),
        0x0A12 => Some("Cambridge Silicon Radio, Ltd."),
        0x0B05 => Some("ASUSTek Computer, Inc."),
        0x0B95 => Some("ASIX Electronics Corp."),
        0x0BDA => Some("Realtek Semiconductor Corp."),
        0x0C45 => Some("Microdia"),
        0x0CF3 => Some("Qualcomm Atheros Communications"),
        0x0D28 => Some("NXP Semiconductors"),
        0x0D8C => Some("C-Media Electronics, Inc."),
        0x0E0F => Some("VMware, Inc."),
        0x0E8D => Some("MediaTek Inc."),
        0x0F0D => Some("Hori Co., Ltd."),
        0x0FC8 => Some("Elmo Semiconductor"),
        0x1004 => Some("LG Electronics Inc."),
        0x1005 => Some("Apacer Technology, Inc."),
        0x1018 => Some("Shuttle Technology Ltd."),
        0x1022 => Some("Advanced Micro Devices, Inc."),
        0x1028 => Some("Dell Inc."),
        0x103C => Some("Hewlett-Packard"),
        0x1050 => Some("Yubico.com"),
        0x1058 => Some("Western Digital Technologies, Inc."),
        0x1059 => Some("Giesecke & Devrient GmbH"),
        0x105B => Some("Foxconn International, Inc."),
        0x1199 => Some("Sierra Wireless, Inc."),
        0x12D1 => Some("Huawei Technologies Co., Ltd."),
        0x1307 => Some("Transcend Information, Inc."),
        0x13FE => Some("Kingston Technology Company Inc."),
        0x1410 => Some("Novatel Wireless"),
        0x1462 => Some("Micro-Star International Co., Ltd."),
        0x1532 => Some("Razer USA, Ltd."),
        0x154B => Some("PNY"),
        0x16C0 => Some("Van Ooijen Technische Informatica"),
        0x17A0 => Some("Samson Technologies Corp."),
        0x17EF => Some("Lenovo"),
        0x18D1 => Some("Google Inc."),
        0x18E3 => Some("Solidtek Corp."),
        0x1915 => Some("Nordic Semiconductor ASA"),
        0x19D2 => Some("ZTE WCDMA Technologies MSM"),
        0x1A40 => Some("Terminus Technology Inc."),
        0x1A86 => Some("QinHeng Electronics"),
        0x1AB1 => Some("Rigol Technologies"),
        0x1B1C => Some("Corsair"),
        0x1B4F => Some("SparkFun Electronics"),
        0x1C4F => Some("SiGma Micro"),
        0x1D50 => Some("OpenMoko, Inc."),
        0x1D6B => Some("Linux Foundation"),
        0x1E3D => Some("Chipsbank Microelectronics Co., Ltd."),
        0x1EAE => Some("ATEN International Co., Ltd."),
        0x1F82 => Some("Audiofly"),
        0x2001 => Some("D-Link Corp."),
        0x2109 => Some("VIA Labs, Inc."),
        0x2341 => Some("Arduino SA"),
        0x2357 => Some("TP-Link"),
        0x239A => Some("Adafruit Industries"),
        0x2717 => Some("Xiaomi Inc."),
        0x2833 => Some("Oculus VR, Inc."),
        0x2A86 => Some("Arduino SA"),
        0x2B24 => Some("Pine64 Inc."),
        0x2C97 => Some("Ledger"),
        0x2D95 => Some("vivo Mobile Communication Co., Ltd."),
        0x2E8A => Some("Raspberry Pi Ltd."),
        0x3938 => Some("MOSART Semiconductor Corp."),
        0x413C => Some("Dell Inc."),
        0x5986 => Some("Acer Inc."),
        0x8087 => Some("Intel Corp."),
        0x8564 => Some("Transcend Information, Inc."),
        _ => None,
    }
}
